<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class WorkOrderSeeder extends Seeder
{
    public function run(): void
    {
        $workOrders = [
            [
                'nomor_wo' => '02-25-ENG-001',
                'nama_pemohon' => 'John Doe',
                'departemen' => 'Engineering',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 2, 10),
                'target_selesai' => Carbon::create(2025, 3, 10),
                'jenis_pekerjaan' => json_encode(['Maintenance Building', 'Cleaning']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Perbaikan AC di ruang server.',
                'status' => 'Open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '02-25-CPP-002',
                'nama_pemohon' => 'Alice Smith',
                'departemen' => 'CPP',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 2, 15),
                'target_selesai' => Carbon::create(2025, 3, 15),
                'jenis_pekerjaan' => json_encode(['Project']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Pembuatan jalur pipa baru.',
                'status' => 'Proses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '03-25-OTH-001',
                'nama_pemohon' => 'Michael Scott',
                'departemen' => 'lainnyas',
                'departemen_lainnya' => 'Research & Development',
                'tanggal_pembuatan' => Carbon::create(2025, 3, 1),
                'target_selesai' => Carbon::create(2025, 4, 1),
                'jenis_pekerjaan' => json_encode(['lainnyas']),
                'jenis_pekerjaan_lainnya' => 'Prototype Testing',
                'deskripsi' => 'Pengujian prototype alat baru.',
                'status' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '03-25-SLI-002',
                'nama_pemohon' => 'Charlie Brown',
                'departemen' => 'Slitting',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 3, 5),
                'target_selesai' => Carbon::create(2025, 4, 5),
                'jenis_pekerjaan' => json_encode(['Ekspedisi']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Pengiriman bahan baku ke pabrik lain.',
                'status' => 'Open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '04-25-LAB-001',
                'nama_pemohon' => 'David Wilson',
                'departemen' => 'Laboratorium',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 4, 12),
                'target_selesai' => Carbon::create(2025, 5, 12),
                'jenis_pekerjaan' => json_encode(['Cleaning', 'Project']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Pembersihan dan upgrade ruang lab.',
                'status' => 'Close',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '05-25-ENG-003',
                'nama_pemohon' => 'Eve Adams',
                'departemen' => 'Engineering',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 5, 1),
                'target_selesai' => Carbon::create(2025, 6, 1),
                'jenis_pekerjaan' => json_encode(['Maintenance Building']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Perbaikan lift.',
                'status' => 'Open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '05-25-HR-004',
                'nama_pemohon' => 'Frank Miller',
                'departemen' => 'HR',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 5, 5),
                'target_selesai' => Carbon::create(2025, 6, 5),
                'jenis_pekerjaan' => json_encode(['Training']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Pelatihan karyawan baru.',
                'status' => 'Proses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '06-25-IT-005',
                'nama_pemohon' => 'Grace Lee',
                'departemen' => 'IT',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 6, 10),
                'target_selesai' => Carbon::create(2025, 7, 10),
                'jenis_pekerjaan' => json_encode(['Upgrade']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Upgrade server.',
                'status' => 'Pending',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '06-25-FIN-006',
                'nama_pemohon' => 'Hank Green',
                'departemen' => 'Finance',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 6, 15),
                'target_selesai' => Carbon::create(2025, 7, 15),
                'jenis_pekerjaan' => json_encode(['Audit']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Audit keuangan tahunan.',
                'status' => 'Open',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nomor_wo' => '07-25-MKT-007',
                'nama_pemohon' => 'Ivy Brown',
                'departemen' => 'Marketing',
                'departemen_lainnya' => null,
                'tanggal_pembuatan' => Carbon::create(2025, 7, 1),
                'target_selesai' => Carbon::create(2025, 8, 1),
                'jenis_pekerjaan' => json_encode(['Campaign']),
                'jenis_pekerjaan_lainnya' => null,
                'deskripsi' => 'Kampanye produk baru.',
                'status' => 'Proses',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('work_orders')->insert($workOrders);
    }
}
